SwargdwariNews/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('newsport.urls',namespace='newsport')),
    path('news/',include('news.urls',namespace='news')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import index

app_name='news'

urlpatterns=[
    path('',index,name="index"),
]

newsport/urls.py
from django.urls import path
from .views import IndexView,detail,factorial


#giving app name
app_name = 'newsport'

urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('details/<int:news_id>/',detail,name="detail"),
    path('news/submit/',factorial,name="submit")
]

news/models.py
from django.db import models

# Create your models here.

newsport/models.py
from django.db import models
from .choices import SPORTS_TYPES
from datetime import datetime

# Create your models here
class Publisher(models.Model):
    name = models.CharField(max_length=200)
    position = models.CharField(max_length=100,blank=True,null=True)
    address = models.CharField(max_length=200,blank=True,null=True)
    phone_no = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media/%y/%m/%d',blank=True)
    email = models.EmailField(blank=True)

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Publisher'
        verbose_name_plural = 'Publishers'


class News(models.Model):
    news_title = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=datetime.now,blank=True)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media/%y/%m/%d',blank=True)
    publisher = models.ForeignKey(Publisher,on_delete=models.DO_NOTHING)
    content = models.TextField()
    subtitle1 = models.TextField(blank=True,null=True)
    content1=models.TextField(blank=True,null=True)
    subtitle2 = models.TextField(blank=True,null=True)
    content2 = models.TextField(blank=True,null=True)

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'



    
    
    

newsport/forms.py
from django import forms

news/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    
    return render(request,'pages/news.html')

newsport/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from .models import News

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'pages/index.html'
    context_object_name = 'recent_news'

    def get_queryset(self):
        return News.objects.order_by('-created_at')[:5]
# def index(request):
#     recent = News.objects.order_by('-created_at')

#     context = {'recent_news':recent,}
#     return render(request,'pages/index.html',context)

def detail(request,news_id):
    full_news = get_object_or_404(News,pk=news_id)
    context = {
        'full_news':full_news

    }
    return render(request,'pages/seeMore.html',context)

def factorial(request):
    n = int(request.GET["num1"])
    def factorialFunc(n): 
        if n == 0:
            return 1
        return n*factorialFunc(n-1)

    z = factorialFunc(n)
    return render(request,"testhtml/test.html",{'calValue':z,'givValue':n})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- font awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- navbar.css -->
        <link rel = "stylesheet" type = "text/css" href="{% static 'css/navbar.css' %}">
        <!-- style.css -->
        <link rel ="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <!-- top bar -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/topbar.css' %}">
        <!-- footer -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
        <title>
            {% block title %}

            {% endblock %}
        </title>
    {% endblock %}
</head>
<body>
    <!-- top bar -->
    {% include 'partials/_topbar.html' %}
    
    <!-- Nab Bar -->
    {% include 'partials/_navbar.html' %}

    <!-- Main content -->
    {% block content %}

    {% endblock %}

    <!-- Footer -->
    {% include 'partials/_footer.html' %}

    <!-- script.js -->
    <script src = "{% static 'js/myscript.js' %}" type="text/javascript"></script>

</body>
</html>

templates/pages/index.html
{% extends 'base.html' %}
  {% block title %}
    Home
  {% endblock %}
{% block content %}


  <!-- slider -->
<!--   
<div class="slideshow-container">

  <div class="mySlides fade">
    <div class="numbertext">1 / 3</div>
    <img src="../../static/img/a.jpg" style="width:100%">
    <div class="text">Caption Text</div>
  </div>
  
  <div class="mySlides fade">
    <div class="numbertext">2/ 3</div>
    <img src="../../static/img/b.jpg" style="width:100%">
    <div class="text">Caption Two</div>
  </div>
  
  <div class="mySlides fade">
    <div class="numbertext">3 / 3</div>
    <img src="../../static/img/c.jpg" style="width:100%">
    <div class="text">Caption Three</div>
  </div>
  
</div>
  <br>
  
  <div style="text-align:center">
    <span class="dot"></span> 
    <span class="dot"></span> 
    <span class="dot"></span> 
  </div> -->
  <!-- end slider -->
  {% for item in recent_news %}
  <div class="Recent">
    <div class="newsBox">
      <p>{{item.news_title}}</p>
     <a href="{% url 'newsport:detail' item.id %}"> <h1>{{item.title}}</h1></a>
      <P>{{item.created_at}}</P>
      <P>{{item.publisher}}</P>
      <img class="themeImage" src="{{item.image.url}}">
      <div>
        {{item.content|safe|truncatewords:"20"|linebreaks}}
        <a href="{% url 'newsport:detail' item.id %}">read more</a>
      </div>
      <!-- <h3>{{item.subtitle1}}</h3>
      <p>{{item.content1}}</p>
      <h3>{{item.subtitle2}}</h3>
      <p>{{item.content2}}</p> -->
      
    </div>
  </div>
  
  {% endfor %}
{% endblock %}

templates/pages/news.html
{% extends 'base.html' %}
{% block content %}
    <form action="submit" method="GET">
        <label> Enter Number:</label>
        <input type="text" name="num1">
        <input type="submit">
        
    </form>
{% endblock %}

templates/pages/seeMore.html
{% extends 'base.html' %}
{% block content %}
    {{ full_news.news_title }}
    {{ full_news.title}}
    
    {{ full_news.created_at}}
    {{ full_news.publisher }}
    <img class="themeImage" src="{{ full_news.image.url}}">
    {{ full_news.content }}
    <h3>{{item.subtitle1}}</h3>
    <p>{{item.content1}}</p>

{% endblock %}

templates/partials/_footer.html
<div class="footer-main-div">
    <div class="footer-social-icons">
        <ul>
            <li><a href="#" target="blank"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" target="blank"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" target="blank"><i class="fa fa-youtube"></i></a></li>
            <li><a href="#" target="blank"><i class="fa fa-instagram"></i></a></li>
        </ul>
    </div>
    <div class="footer-menu-one">
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">News</a></li>
            <li><a href="#">Sports</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">About</a></li>
        </ul>
    </div>
    <div class="footer-menu-two">
        <ul>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Gallery</a></li>
            <li><a href="#">Media</a></li>
            <li><a href="#">Contact Us</a></li>
        </ul>
    </div>

</div>
<div class="footer-bottom">
    <p>All right reserved:&copy;<a href="#">Er Sharad Bhandari</a></p>
</div>

templates/partials/_navbar.html
<div class="topnav" id="mytopnav">
        <a href="{% url 'newsport:index' %}" class="active">Home</a>
        <a href="{% url 'news:index' %}">News</a>
        <div class="subMenu">
            <button class="dropbtn">News24</button>
            <div class="dropbtn-content">
                <a href="#Football">national</a>
                <a href="#Cricket">international</a>
                <a href="#Volleyball">local</a>
            </div>
        </div>
        <div class="subMenu">
            <button class="dropbtn">Sports</button>
            <div class="dropbtn-content">
                <a href="#Football">Football</a>
                <a href="#Cricket">Cricket</a>
                <a href="#Volleyball">Volleyball</a>
            </div>
        </div>
        <div class="subMenu">
            <button class="dropbtn">Events</button>
            <div class="dropbtn-content">
                <a href="#Football">public</a>
                <a href="#Cricket">private</a>
                <a href="#Volleyball">government</a>
            </div>
        </div>
        <a href="#Contact">Contact</a>
        <a href="#About">About</a>
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
        </a>

</div>

templates/partials/_topbar.html
 <!-- Top Bar -->
{% load static %}
<div class="topSocial">
     <a href="#latest"><i class="fa fa-bolt" style="color: black;" aria-hidden="true"> Latest news </i></a>
     <div class="srhFunction">
          <input type="text" placeholder="Search.." name="search">
          <button type="submit"><i class="fa fa-search"></i></button>
      </div>     
</div>
<div class="header">
    <div class="col-md-12">
        <div class="col-md-3">
            <a href="#default" class="logo">Engineering <small>Concern</small> </a>
        </div>
            <div class="banner">
                <div class="addContainer">
                    <img src="../../static/img/school.jpg" alt="banner">
                </div>
            </div>
            <div class="header-right">
                <a href="#facebook"><i class="fa fa-facebook-official" style="color: blue;" aria-hidden="true"></i></a>
                <a href="#youtube"><i class="fa fa-youtube-play" style="color: red;" aria-hidden="true"></i></a>
                <a href="#twitter"><i class="fa fa-twitter" style="color: #00acee;" aria-hidden="true"></i></a>
                <a href="#instagram"><i class="fa fa-instagram" style="color: #F77737;" aria-hidden="true"></i></a>
            </div>
    </div>
</div>

templates/testhtml/test.html
<h1>tha factorial of {{ givValue }} is {{ calValue }}</h1>